globalThis.process ??= {};
globalThis.process.env ??= {};
import { C as createAstro, d as renderTemplate, f as maybeRenderHead, m as addAttribute } from "./server_BKqYvUrJ.mjs";
import { t as createComponent } from "./compiler_BzXqPCge.mjs";
//#region src/components/CategorySelect.astro
createAstro("https://astro.build");
var $$CategorySelect = createComponent(($$result, $$props, $$slots) => {
	const Astro = $$result.createAstro($$props, $$slots);
	Astro.self = $$CategorySelect;
	const { selected = "", required = true } = Astro.props;
	return renderTemplate`${maybeRenderHead($$result)}<select name="category"${addAttribute(required, "required")} class="w-full px-4 py-2.5 border border-stone-300 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent transition"><option value="">Select a category…</option><optgroup label="── International Public Law"><option value="international-law"${addAttribute(selected === "international-law", "selected")}>🏛️  International Law</option><option value="human-rights-law"${addAttribute(selected === "human-rights-law", "selected")}>✊  International Human Rights Law</option><option value="humanitarian-law"${addAttribute(selected === "humanitarian-law", "selected")}>🕊️  International Humanitarian Law</option><option value="international-criminal-law"${addAttribute(selected === "international-criminal-law", "selected")}>⚖️  International Criminal Law</option><option value="international-trade-law"${addAttribute(selected === "international-trade-law", "selected")}>🤝  International Trade Law</option><option value="international-environmental-law"${addAttribute(selected === "international-environmental-law", "selected")}>🌿  International Environmental Law</option><option value="maritime-law"${addAttribute(selected === "maritime-law", "selected")}>⚓  International Maritime Law</option></optgroup><optgroup label="── Specialised Fields"><option value="international-investment-law"${addAttribute(selected === "international-investment-law", "selected")}>📈  International Investment Law</option><option value="diplomatic-law"${addAttribute(selected === "diplomatic-law", "selected")}>🎖️  Diplomatic &amp; Consular Law</option><option value="air-space-law"${addAttribute(selected === "air-space-law", "selected")}>🚀  Air &amp; Space Law</option><option value="refugee-law"${addAttribute(selected === "refugee-law", "selected")}>🏳️  International Refugee Law</option><option value="international-labor-law"${addAttribute(selected === "international-labor-law", "selected")}>🏗️  International Labour Law</option><option value="intellectual-property-law"${addAttribute(selected === "intellectual-property-law", "selected")}>💡  International IP Law</option></optgroup><optgroup label="── General &amp; Comparative"><option value="river-law"${addAttribute(selected === "river-law", "selected")}>🌊  River &amp; Water Law</option><option value="world-law"${addAttribute(selected === "world-law", "selected")}>🌍  World Law</option></optgroup></select>`;
}, "C:/Users/Esstha/Music/law/lex-researcher-site/src/components/CategorySelect.astro", void 0);
//#endregion
export { $$CategorySelect as t };
